version : "3"
services:
    figma-plugin:
        build:
            context : .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - ./:/app
    
